CREATE TABLE `users` (
	`id` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`account` BIGINT(19) NOT NULL,
	`password` BIGINT(19) NOT NULL,
	`name` BIGINT(19) NOT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `id` (`id`) USING BTREE
);